const READ_WALLET_SCOPE = "read:wallet";
const WRITE_WALLET_SCOPE = "write:wallet";
const AUTHORIZATION_CODE_GRANT = "authorization_code";
const REFRESH_TOKEN_GRANT = "refresh_token";
const JWT_SECRET = "TFGvLpD1sTkY3G11xKtElbB6i5CIAhbF";
const JWT_LIFETIME = "1d";
module.exports = {READ_WALLET_SCOPE, WRITE_WALLET_SCOPE, AUTHORIZATION_CODE_GRANT, REFRESH_TOKEN_GRANT, JWT_SECRET, JWT_LIFETIME};
